

Parameters:
  EcsClusterName:
    Type: String
    Description: "MyECSCluster"
    
Resources:
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref EcsClusterName
  
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-ecs-task
      ContainerDefinitions:
        - Name: python
          Image: public.ecr.aws/c0i1q1a6/python1
          Cpu: 1024
          Memory: 2048
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: 'true'
              awslogs-group: /ecs/python
              awslogs-region: ap-northeast-2
              awslogs-stream-prefix: ecs
      TaskRoleArn: 'arn:aws:iam::764581325448:role/ecsTaskExecutionRole'
      ExecutionRoleArn: 'arn:aws:iam::764581325448:role/ecsTaskExecutionRole'
      NetworkMode: awsvpc
      Cpu: '1024'
      Memory: '2048'
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX

  MyECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      ServiceName: MyECSService
      TaskDefinition: !Ref MyTaskDefinition
      DesiredCount: 0
      LaunchType: EC2  # or FARGATE if using AWS Fargate
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [subnet-0a52b6fa727fd8373, subnet-0d7565e71720786c4, subnet-0d8dd55e15e0dd7bb]
          SecurityGroups:
            - sg-047aef611e4acc3f2
   
   
  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: MyASG
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: 1
      MaxSize: 3
      VPCZoneIdentifier: [subnet-0a52b6fa727fd8373, subnet-0d7565e71720786c4, subnet-0d8dd55e15e0dd7bb]
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
   
   
  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-074413845c101fc4d  # Replace with your AMI ID
      InstanceType: t3a.medium  # Replace with your instance type
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${MyECSCluster} >> /etc/ecs/ecs.config
            
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalencer
      Subnets: [subnet-0a52b6fa727fd8373, subnet-0d7565e71720786c4, subnet-0d8dd55e15e0dd7bb, subnet-00ab23b459bbf5cfa]
      SecurityGroups: [sg-08d1cabb5c0dfbe95]
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
    
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Protocol: HTTP
      Port: 80
      VpcId: vpc-0faec33d73eb1d105
      TargetType: instance
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: MyTargetGroup
  
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            StatusCode: 200
            ContentBody: "OK"
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: text/plain
            ContentBody: "OK"
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            StatusCode: 200
            ContentBody: "OK"
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 443
      Protocol: HTTPS
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: text/plain
            ContentBody: "OK"
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: "arn:aws:acm:ap-northeast-2:764581325448:certificate/581c399b-26bd-4a07-8883-77f83759c490"  # Replace with your SSL certificate ARN
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref MyTargetGroup
                Weight: 1
                
           
  EcsCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EcsCpuAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 80
      ActionsEnabled: true
      AlarmActions:
        - !Ref MySNSTopic
      Dimensions:
        - Name: ClusterName
          Value: !Ref MyECSCluster

  EcsMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: EcsMemoryAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 2
      MetricName: MemoryUtilization
      Namespace: AWS/ECS
      Period: 300
      Statistic: Average
      Threshold: 80
      ActionsEnabled: true
      AlarmActions:
        - !Ref MySNSTopic
      Dimensions:
        - Name: ClusterName
          Value: !Ref MyECSCluster

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MySNSTopic
      TopicName: MySNSTopic

  MySNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref MySNSTopic
      Endpoint: sooryavanshirup@gmail.com    



  MyApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: MyApi
      Description: 'API Gateway pointing to Load Balancer'

  MyApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: '{proxy+}'

  MyApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      ResourceId: !Ref MyApiResource
      RestApiId: !Ref MyApi
      Integration:
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: !Sub 'http://${MyLoadBalancer.DNSName}/{proxy}'
      MethodResponses:
        - StatusCode: 200

  MyDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: MyApiMethod
    Properties:
      RestApiId: !Ref MyApi
      StageName: 'prod'

